lexik_jwt_authentication:
#    private_key_path: '%kernel.project_dir%/%env(resolve:JWT_PRIVATE_KEY_PATH)%'
#    public_key_path: '%kernel.project_dir%/%env(resolve:JWT_PUBLIC_KEY_PATH)%'
#    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    private_key_path: '%kernel.project_dir%/var/jwt/private.pem'
    public_key_path: '%kernel.project_dir%/var/jwt/public.pem'
    pass_phrase: 'youshallnotpass'